# --------------------------------------
# 通用配置

# menu
menu:

# --------------------------------------
# 网站相关

# abbrlink 永久链接
## 使用此功能请卸载 hexo-abbrlink 和 hexo-abbrlink2 等类似重复功能插件，它们与该主题的主副标题特性并不兼容
## 如果文章路径和文件名使用全英文，不建议开启此功能，建议在 hexo 的_config.yml 文件中使用 permalink: :title.html
## 否则建议开启此功能，则在 hexo 的_config.yml 文件中如下配置
##    permalink: :abbrlink.html or permalink: :abbrlink/
## or permalink: posts/:abbrlink.html or permalink: posts/:abbrlink/
abbrlink:
  enable: true
# 网站图标
favicon: /img/favicon.png
# 是否启用黑夜模式
default_display_mode: light # light or dark

# --------------------------------------
# 美化相关

# font
global_font_family: "'LXGW WenKai Screen', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Lato, Roboto, 'PingFang SC', 'Microsoft YaHei', sans-serif"
# 白天模式
lightmode_style:
# 黑夜模式
darkmode_style:

# highlight
## 启用 highlight.js 官方主题需设置 hexo 配置文件中 highlight.hljs: true
## 并自行在 inject.head 中引入主题 css

# --------------------------------------
# 优化相关

# css前缀
css_prefix: true

# --------------------------------------
# js plugin and cdn

# cdn
# 主题cdn
# 通用
main_css: /css/main.css
main_js: /js/main.js

# home
home_css:
home_js:
# page
page_css:
page_js:
# post
post_css:
post_js:
# tag
tag_css:
tag_js:
# category
category_css:
category_js:
# archive
archive_css:
archive_js:
# 404
404_css:

# font cdn
global_font_family_cdn: https://cdn1.tianli0.top/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

# Inject
## 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>